name: CI

on:
  push:

permissions:
  contents: read
  packages: write

env:
  FORCE_COLOR: 1

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare Earthly
      uses: ./.github/actions/setup_earthly
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run dialyzer
      run: earthly --ci --push +linter

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare Earthly
      uses: ./.github/actions/setup_earthly
      with:
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run test
      run: earthly --ci --push +test
